<a href="https://colab.research.google.com/github/TamaMahasiswa/preprocessingdata/blob/main/preprocessingdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Langkah Awal sebslum kita menjalankan preprocessingdata, kita harus menginport library seperti di bawah ini:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Setelah mengimpor library, langkah berikutnya adalah membaca data dari file CSV yang berisi nilai X dan Y.

In [ ]:
dataset = pd.read_csv('data_pembelian.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

menjalankan printah untuk membaca nilai X

In [ ]:
print(x)

[['Indonesia' 25.0 5000000.0]
 ['Malaysia' 30.0 nan]
 ['Singapura' nan 7000000.0]
 ['Indonesia' 35.0 8000000.0]
 ['Malaysia' nan 9000000.0]
 ['Singapura' 45.0 10000000.0]
 ['Indonesia' 50.0 nan]
 ['Malaysia' 55.0 12000000.0]
 ['Singapura' 32.0 6500000.0]
 ['Indonesia' nan 7200000.0]
 ['Malaysia' 42.0 8300000.0]
 ['Singapura' 37.0 9100000.0]
 ['Indonesia' 46.0 9700000.0]
 ['Malaysia' 31.0 nan]
 ['Singapura' nan 8600000.0]
 ['Indonesia' 27.0 6300000.0]
 ['Malaysia' 48.0 10200000.0]
 ['Singapura' 26.0 5800000.0]
 ['Indonesia' 39.0 nan]
 ['Malaysia' nan 11200000.0]]


menjalankan printah untuk membaca nilai y

In [ ]:
print(y)

['Ya' 'Tidak' 'Ya' nan 'Tidak' 'Ya' 'Tidak' 'Ya' 'Tidak' 'Ya' nan 'Ya'
 'Tidak' 'Ya' 'Tidak' nan 'Tidak' 'Ya' 'Tidak' 'Ya']


Jika terdapat nilai yang hilang dalam dataset, kita akan mengisinya dengan nilai rata-rata (mean) dari masing-masing kolom.

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

Ketika kita menjalankan kode `print(X)`, program akan menampilkan data X setelah proses pengisian nilai yang hilang dengan rata-rata (mean). Ini berguna untuk memastikan bahwa semua nilai yang hilang telah terisi dengan benar dan dataset siap digunakan untuk analisis lebih lanjut.

In [ ]:
print(x)

[['Indonesia' 25.0 5000000.0]
 ['Malaysia' 30.0 8368750.0]
 ['Singapura' 37.86666666666667 7000000.0]
 ['Indonesia' 35.0 8000000.0]
 ['Malaysia' 37.86666666666667 9000000.0]
 ['Singapura' 45.0 10000000.0]
 ['Indonesia' 50.0 8368750.0]
 ['Malaysia' 55.0 12000000.0]
 ['Singapura' 32.0 6500000.0]
 ['Indonesia' 37.86666666666667 7200000.0]
 ['Malaysia' 42.0 8300000.0]
 ['Singapura' 37.0 9100000.0]
 ['Indonesia' 46.0 9700000.0]
 ['Malaysia' 31.0 8368750.0]
 ['Singapura' 37.86666666666667 8600000.0]
 ['Indonesia' 27.0 6300000.0]
 ['Malaysia' 48.0 10200000.0]
 ['Singapura' 26.0 5800000.0]
 ['Indonesia' 39.0 8368750.0]
 ['Malaysia' 37.86666666666667 11200000.0]]


Kita akan mengubah data kategorikal menjadi bentuk numerik menggunakan One-Hot Encoding. Metode ini akan mengonversi setiap kategori unik dalam kolom menjadi vektor biner, sehingga data lebih mudah diproses oleh algoritma machine learning.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

Saat kita menjalankan `print(X)`, program akan menampilkan data X setelah dikonversi menggunakan One-Hot Encoding. Ini memungkinkan kita untuk melihat bagaimana data kategorikal telah diubah menjadi bentuk numerik dengan representasi vektor biner.

In [ ]:
print(x)

[[1.0 0.0 0.0 25.0 5000000.0]
 [0.0 1.0 0.0 30.0 8368750.0]
 [0.0 0.0 1.0 37.86666666666667 7000000.0]
 [1.0 0.0 0.0 35.0 8000000.0]
 [0.0 1.0 0.0 37.86666666666667 9000000.0]
 [0.0 0.0 1.0 45.0 10000000.0]
 [1.0 0.0 0.0 50.0 8368750.0]
 [0.0 1.0 0.0 55.0 12000000.0]
 [0.0 0.0 1.0 32.0 6500000.0]
 [1.0 0.0 0.0 37.86666666666667 7200000.0]
 [0.0 1.0 0.0 42.0 8300000.0]
 [0.0 0.0 1.0 37.0 9100000.0]
 [1.0 0.0 0.0 46.0 9700000.0]
 [0.0 1.0 0.0 31.0 8368750.0]
 [0.0 0.0 1.0 37.86666666666667 8600000.0]
 [1.0 0.0 0.0 27.0 6300000.0]
 [0.0 1.0 0.0 48.0 10200000.0]
 [0.0 0.0 1.0 26.0 5800000.0]
 [1.0 0.0 0.0 39.0 8368750.0]
 [0.0 1.0 0.0 37.86666666666667 11200000.0]]


Kita akan mengonversi data kategorikal menjadi bentuk numerik menggunakan Label Encoding. Metode ini menggantikan setiap kategori unik dengan angka tertentu, sehingga data dapat digunakan dalam pemrosesan machine learning.

In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y=le.fit_transform(y)

Saat kita menjalankan `print(y)`, program akan menampilkan data y setelah dikonversi menggunakan Label Encoding. Ini memungkinkan kita melihat bagaimana setiap kategori telah digantikan dengan nilai numerik.

In [ ]:
print(y)

[1 0 1 2 0 1 0 1 0 1 2 1 0 1 0 2 0 1 0 1]


Kita akan membagi dataset menjadi data latih (training) dan data uji (testing) agar model machine learning dapat belajar dari data latih dan dievaluasi menggunakan data uji.

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

Saat kita menjalankan `print(X_train)`, program akan menampilkan data latih (training) setelah proses pembagian dataset. Data ini digunakan oleh model machine learning untuk belajar pola dari dataset.

In [ ]:
print(x_train)

[[0.0 0.0 1.0 37.86666666666667 7000000.0]
 [0.0 0.0 1.0 37.86666666666667 8600000.0]
 [0.0 1.0 0.0 37.86666666666667 9000000.0]
 [0.0 0.0 1.0 26.0 5800000.0]
 [0.0 1.0 0.0 55.0 12000000.0]
 [0.0 1.0 0.0 30.0 8368750.0]
 [0.0 1.0 0.0 31.0 8368750.0]
 [1.0 0.0 0.0 25.0 5000000.0]
 [0.0 1.0 0.0 37.86666666666667 11200000.0]
 [1.0 0.0 0.0 39.0 8368750.0]
 [1.0 0.0 0.0 37.86666666666667 7200000.0]
 [1.0 0.0 0.0 27.0 6300000.0]
 [0.0 0.0 1.0 32.0 6500000.0]
 [1.0 0.0 0.0 46.0 9700000.0]
 [0.0 0.0 1.0 37.0 9100000.0]
 [0.0 0.0 1.0 45.0 10000000.0]]


Saat kita menjalankan `print(X_test)`, program akan menampilkan data uji (testing) setelah proses pembagian dataset. Data ini digunakan untuk menguji kinerja model setelah dilatih.

In [ ]:
print(x_test)

[[1.0 0.0 0.0 35.0 8000000.0]
 [0.0 1.0 0.0 48.0 10200000.0]
 [1.0 0.0 0.0 50.0 8368750.0]
 [0.0 1.0 0.0 42.0 8300000.0]]


Saat kita menjalankan `print(y_train)`, program akan menampilkan data latih (training) untuk variabel target (y). Data ini digunakan oleh model machine learning untuk belajar dan menemukan pola dari dataset.

In [ ]:
print(y_train)

[1 0 0 1 1 0 1 1 1 0 1 2 0 0 1 1]


Saat kita menjalankan `print(y_test)`, program akan menampilkan data uji (testing) untuk variabel target (y). Data ini digunakan untuk mengukur seberapa baik model dapat memprediksi hasil berdasarkan data yang belum pernah dilihat sebelumnya.

In [ ]:
print(y_test)

[2 0 0 2]


Kita akan menstandarisasi fitur numerik dalam dataset menggunakan **StandardScaler** dari `sklearn.preprocessing`. Metode ini mengubah data sehingga memiliki rata-rata 0 dan standar deviasi 1, sehingga model machine learning dapat bekerja lebih optimal.

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:]= sc.transform(x_test[:, 4:])

Saat kita menjalankan `print(X_train)`, program akan menampilkan data latih (training) setelah proses standarisasi. Data ini telah diubah sehingga memiliki rata-rata 0 dan standar deviasi 1, membantu model machine learning bekerja lebih optimal.

In [ ]:
print(x_train)

[[0.0 0.0 1.0 37.86666666666667 -0.6884003376627703]
 [0.0 0.0 1.0 37.86666666666667 0.17099855994975857]
 [0.0 1.0 0.0 37.86666666666667 0.3858482843528908]
 [0.0 0.0 1.0 26.0 -1.332949510872167]
 [0.0 1.0 0.0 55.0 1.9972212173763826]
 [0.0 1.0 0.0 30.0 0.04678856302919774]
 [0.0 1.0 0.0 31.0 0.04678856302919774]
 [1.0 0.0 0.0 25.0 -1.7626489596784316]
 [0.0 1.0 0.0 37.86666666666667 1.5675217685701182]
 [1.0 0.0 0.0 39.0 0.04678856302919774]
 [1.0 0.0 0.0 37.86666666666667 -0.5809754754612042]
 [1.0 0.0 0.0 27.0 -1.0643873553682517]
 [0.0 0.0 1.0 32.0 -0.9569624931666857]
 [1.0 0.0 0.0 46.0 0.7618353020583722]
 [0.0 0.0 1.0 37.0 0.43956071545367387]
 [0.0 0.0 1.0 45.0 0.9229725953607214]]
